# Generated by Django 3.2.15 on 2022-11-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineID', models.CharField(max_length=255)),
                ('lineID', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('tag_id', models.CharField(max_length=255)),
                ('register', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('BIT', 'BIT'), ('INT', 'INT'), ('FLOAT', 'FLOAT'), ('ASCII', 'ASCII')], max_length=255)),
                ('display', models.CharField(choices=[('BUTTON', 'BUTTON'), ('INDICATOR', 'INDICATOR'), ('TEXT', 'TEXT'), ('NUMBER', 'NUMBER')], max_length=255)),
                ('asg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
            ],
        ),
    ]
